import java.util.*
import java.*;
import kotlin.random.*;
// การใช้คำสั่ง finally
// คำสั่ง finally ใช้สำหรับกำหนดบล็อกที่จะดำเนินการเสมอ ไม่ว่าจะเกิดข้อผิดพลาด
// หรือไม่ก็ตาม ซึ้งรูปแบบโดยทั่วไปเราจะวางบล็อก finally ไว้ถัดจากบล็อก catch
/*
*  try {
* } catch (...) {
* } finally {
*  // สิ่งที่ต้องการให้ทำเสมอ ไม่ว่าจะเกิดข้อผิดพลาดหรือไม่ก็ตาม
* }
*
* ในบางกรณี แม้จะมีข้อผิดพลาดที่เกิดขึ้น หากเราไม่มีวิธีจัดการใดๆ แต่มีสิ่งที่ต้องดำเนินการเสอ
*  ไม่ว่าจะเกิดข้อผิดพลาดหรือไม่ก็ตาม ก็อาจจะใช้แค่ try กับ finally โดยตัดบล็อก catch
*  ออกไป
*  try {
* } finally {
* }
*  หากเรานำบล็อก try-catch-finally ไปใช้งานในแบบ Expression คำสั่งในบล็อก finally
*  จะไม่มีผลใดๆ ดังนั้น กรณีดังกล่าว จึงควรใช้เฉพาะ try-catch เท่านั้น แต่ไม่ควรใช้ finally
*   ร่วมด้วย
* */
fun main(args: Array<String>) {

}
